### ISSUE TITLE
Overall university rank

### ISSUE THREAD

**Issue by ishaankumar50** [ankushgarg1998/ipu-ranklist#11]
Please update and kindly add university rank section. Otherwise your project is lit. Keep up the good work.

**Comment by ankushgarg1998** [comment]
That's a good suggestion. Will to bring it up soon. :spiral_notepad: 

And thanks. I'm glad it helped you. :smile:

**Comment by ankushgarg1998** [comment]
Added the University Ranklist feature. 🔥 
Give it a try @ishaankumar50 
https://www.ipuranklist.com/university-ranklist

**Comment by ankushgarg1998** [comment]
This issue is resolved.
Further work will be tracked in #51
