### ISSUE TITLE
BALLB 9th semester result 2017-2022

### ISSUE THREAD

**Issue by Aanchal229** [ankushgarg1998/ipu-ranklist#126]
Hey, 

the result for Private international law, paper code 038515, 9th Semester (for batch 2017-2022) was revised and released again for all. 
can you update the same on the website as it will be helpful for everyone? 

Hopefully you will correct the error on the website. 

Thank you

**Comment by ankushgarg1998** [comment]
Hi @Aanchal229 

The following 3 LLB PDFs have just been synced:
[Exam (Dec. 2021) Rechecking Result LLB, Enrol. No.47125503817](http://ggsipu.ac.in/ExamResults/2022/150722/Rechecking%20Result_Epsita%20Agastya_LLB_Declared%20Result_Dec2021.pdf)
[Exam (Dec. 2021) Revised Result for LLB, 9th Semester (Technical Glitch)](http://ggsipu.ac.in/ExamResults/2022/140722/Glitch_035_038_Declared%20Result_Dec2021.pdf)
[Exam (Dec. 2021) Revised Result for LLB](http://ggsipu.ac.in/ExamResults/2022/130722/Revised_35515_38515_LLB_Declared%20Result_Dec2021.pdf)

Please check if your query is resolved.

**Comment by ankushgarg1998** [comment]
Closing this issue now, due to no response. Hoping your issue was resolved. @Aanchal229
