### ISSUE TITLE
Not fetching data 

### ISSUE THREAD

**Issue by varunkrma** [ankushgarg1998/ipu-ranklist#127]
Website is not fetching data, please do something fast 🥲 i have to upload marksheet for branch upgradation.

**Comment by neelam6784** [comment]
Yes please fix this soon, I have to also upload my marksheet for placement. :(

**Comment by ankushgarg1998** [comment]
Hi folks. Thanks for reporting. Let me check.

**Comment by ankushgarg1998** [comment]
@varunkrma 
@neelam6784 
The issue should be fixed now. Could you please check & respond?

**Comment by ankushgarg1998** [comment]
Closing this issue now, due to no response. Hoping this is resolved.
