### ISSUE TITLE
The result did not update after clearing backlog.

### ISSUE THREAD

**Issue by Crimsonpixie** [ankushgarg1998/ipu-ranklist#129]

**Comment by ankushgarg1998** [comment]
Hi @Crimsonpixie 
Please share the details.

Which course? Which batch?
When was the result PDF uploaded to the official IPU website?

**Comment by ankushgarg1998** [comment]
Closing this issue as no data was shared.

**Comment by ankushgarg1998** [comment]
Please feel free to reopen it, if needed.
