### ISSUE TITLE
Wrong Subject Name

### ISSUE THREAD

**Issue by gauravjain2** [ankushgarg1998/ipu-ranklist#130]
Hi
For subject code HS-402 for USICT B.Tech 8th Semester, the actual subject name is "Technical Writing", but it is showing "Human Values and Professional Ethics II" 
Please update the same.

**Comment by ankushgarg1998** [comment]
Hey @gauravjain2 
Let me check.
Could you share the paperID as well?

Could be a case of #87

**Comment by gauravjain2** [comment]
Hi @ankushgarg1998 , the paperID is 98402 and the subject code is HS-402.
Yeah, it might be a case of #87 

Subject: Technical Writing
paperID: 98402
subjectCode: HS-402

Subject: Human Values and Professional Ethics II
paperID: 98402
subjectCode: ETHS-402


> Observation: 
> To add on, despite having the same paperID, both subjects have an entirely different syllabus.
> 
> I think, you have made paperID as primary key in the Database, you can probably go with the combination of paperID and subjectCode as the primary key

**Comment by ankushgarg1998** [comment]
Agreed @gauravjain2 

It needs to be a composite index:
Either (paperId, subjectCode) OR (paperId, admissionYear).

Need to find data & examples to make a judicious choice between these two.

**Comment by gauravjain2** [comment]
The admission year might not work. Because in same admission year (like in
the present case) we had same I'd. I'll check a few other corner cases
around this issue and will get back to you.

**Comment by ankushgarg1998** [comment]
Oh is it? Are these two subjects of the same batch but different semesters?

Thanks. Please do. It'll be very helpful.

**Comment by ankushgarg1998** [comment]
Hi @gauravjain2 
Were you able to check this?
I was thinking of building a solution around this, over this long weekend.

**Comment by ankushgarg1998** [comment]
Hi @gauravjain2 

This fix for this issue has been deployed. ✅ 
Please verify. Thanks.
