### ISSUE TITLE
USAR is not in the database.

### ISSUE THREAD

**Issue by aviraj1729** [ankushgarg1998/ipu-ranklist#148]
GGSIPU's new school is not added to the database of IPU ranklist so please assign me to add it to the same

**Comment by ankushgarg1998** [comment]
Hey @Hawkjack1729 
Are you sure you're checking the "USIT B.Tech" page and not the "B.Tech." page by mistake?

https://www.ipuranklist.com/ranklist/usit-btech

![IMG_20230307_074953.jpg](https://user-images.githubusercontent.com/22600172/223302642-469d4864-59b2-4c07-98b8-347069085745.jpg)

**Comment by ankushgarg1998** [comment]
@Hawkjack1729 Can you confirm if your issue is resolved? I'll close this it in that case.

**Comment by aviraj1729** [comment]
yes it's there now and you can close this issue
