### ISSUE TITLE
CGPA is actually SGPA

### ISSUE THREAD

**Issue by AkshitAggarwal** [ankushgarg1998/ipu-ranklist#15]
When it's calculating CGPA for each semester it's basically calculating the SGPA which is the GPA for that semester and CGPA (Cumulative GPA) is GPA for every semester from 1 to that particular one.

**Comment by ankushgarg1998** [comment]
O shit :rofl: You're right.
Thanks a lot man. Will correct it in the next update.

**Comment by ankushgarg1998** [comment]
I believe https://github.com/ankushgarg1998/ipu-ranklist/commit/452d3512f0000e070dd483418a9e66501d8d8bbd fixes this.

Please feel free to reopen this issue or create a new one if any changes are required.
