### ISSUE TITLE
Query Parameter not updating in the site 

### ISSUE THREAD

**Issue by programerr01** [ankushgarg1998/ipu-ranklist#153]
hii, when i go to `https://www.ipuranklist.com/ranklist/btech?batch=21&sem=0&college=MAIT&shift=0&branch=CSE`
it does select college, branch , shift and sem but it's not updating batch by itself 

![image](https://github.com/ankushgarg1998/ipu-ranklist/assets/61112300/e968888b-a894-4a63-8c05-c798c5933dbd)

**Comment by ankushgarg1998** [comment]
Hi @programerr01 
Thanks for reporting this.

Seems it's loading the correct result, but showing the incorrect batch in the dropdown.
I'll check this and revert.

**Comment by ankushgarg1998** [comment]
Hi @programerr01 
This is fixed. Please verify.
