### ISSUE TITLE
Miscalculated Credit Points

### ISSUE THREAD

**Issue by AshutoshSharan01** [ankushgarg1998/ipu-ranklist#154]
The result of 10th semester B.A.LLB and BBA.LLB has great discrepancy. The credit points awarded for dissertation is 20 points however it is calculated as 2 points leading to discrepancy in overall GPA calculation.

**Comment by ankushgarg1998** [comment]
Hi @AshutoshSharan01 
Thanks for informing. Lemme fix that.

**Comment by ankushgarg1998** [comment]
Hi @AshutoshSharan01 
I've fixed it. Please check now.
