### ISSUE TITLE
Reappear result not updated

### ISSUE THREAD

**Issue by Kushagrkapoor** [ankushgarg1998/ipu-ranklist#16]

**Comment by ankushgarg1998** [comment]
Yes, that feature is yet to be implemented.
Will do it soon.
Thanks for raising the issue.

**Comment by ankushgarg1998** [comment]
@Kushagrkapoor The reappear result has been updated for all batches/ branches. Please verify. :)

**Comment by Kushagrkapoor** [comment]
Thank you for your response.
