### ISSUE TITLE
Backlog not updated 

### ISSUE THREAD

**Issue by satvikmehan** [ankushgarg1998/ipu-ranklist#160]
Subject with backlog is counted as another subject(showing 2 subjects 1 with backlog and 1 with reappeaer )which is affecting the cgpa.
Please check on that.

**Comment by ankushgarg1998** [comment]
Hi @satvikmehan 

Thanks for raising this issue with me.
Apparently, this is due to incorrect paper_id being selected for a paper_code.
This issue has the same root-cause due to which #150 occurs.

I'm close to finishing the build for fixing these issues.

ETA: March End.

**Comment by satvikmehan** [comment]
Any update?

**Comment by satvikmehan** [comment]
Bro please fix this,it's in 1 sem only

**Comment by ankushgarg1998** [comment]
Hi @satvikmehan 
The fix is taking longer than I'd anticipated.
It is in the final stages now. It will be deployed by the time this result season is over.

**Comment by ankushgarg1998** [comment]
Hi @satvikmehan 

This fix for this issue has been deployed. ✅ 
Please verify. Thanks.
