### ISSUE TITLE
No_college in institute section 

### ISSUE THREAD

**Issue by Khanak-Gupta** [ankushgarg1998/ipu-ranklist#165]
Students those took admission in directly second year such as lateral entry students. In there institute section no college appears also they are not included in there batch ranklist this is mostly done to the dwarka campus students

**Comment by ankushgarg1998** [comment]
Hi @Khanak-Gupta 
Thank you for reporting this. There's a large patch for subject names about to be deployed by the end of June, which includes fixes related to institute management as well. This should be fixed with that. Will update here.

**Comment by ankushgarg1998** [comment]
Hi @Khanak-Gupta 

This fix for this issue has been deployed. ✅ 
Please verify. Thanks.
