### ISSUE TITLE
Wrong Subjects on sem 6 results of AIDS BRANCH of 2021-2025 BATCH 

### ISSUE THREAD

**Issue by Keshav10934** [ankushgarg1998/ipu-ranklist#167]
Wring subject names are displayed in sem 6 results of AIDS BRANCH BTECH of 2021-2025 batch especially at VIPS COLLEGE , in both electives and core subjects , subjects if names like visual basic net , unformation theory and coding are appearing which are wrong and there are many subjects like that

**Comment by ankushgarg1998** [comment]
Hi @Keshav10934 
This is a known issue, being tracked here: https://github.com/ankushgarg1998/ipu-ranklist/issues/150

**Comment by ankushgarg1998** [comment]
Hi @Keshav10934 

This fix for this issue has been deployed. ✅ 
Please verify. Thanks.
