### ISSUE TITLE
Error in IPU Ranklist, ADGITM Morning 2023-2027 , CST, Sem 2

### ISSUE THREAD

**Issue by ipu2796** [ankushgarg1998/ipu-ranklist#168]
This is to bring to your kind notice that there is an error in the IPU Ranklist of sem 2 , 2023-2027 batch of CST ,ADGITM 
The rank of 01215612723 should be higher than that of 04215612723 as per attached images.
Kindly get it rectified as soon as possible. 
Hope that you will revert back.
![1](https://github.com/user-attachments/assets/929a1b80-7afa-4faf-8b62-e39cc9e1f373)
![2](https://github.com/user-attachments/assets/2a1436bb-fc45-46d5-8c93-dcb9d7e58dfe)

**Comment by ankushgarg1998** [comment]
Hi @ipu2796 
Please refer to the GPA calculation logic. 
https://github.com/ankushgarg1998/ipu-ranklist/wiki/SGPA-and-CGPA-calculation

If you wish to see the rank list by percentage criteria. Please select that.
<img width="1407" alt="Screenshot 2024-07-28 at 9 16 47 PM" src="https://github.com/user-attachments/assets/8bed8264-dfb1-4b4a-951a-a8fe83e1ac93">
