### ISSUE TITLE
USICT students are left out

### ISSUE THREAD

**Issue by Eshaan7** [ankushgarg1998/ipu-ranklist#18]
Great work but please include data for USICT Btech students as well. Since we get our result in a different pdf, I am sure that with a little changes in your parser, it will work flawlessly.

**Comment by ankushgarg1998** [comment]
Yep. I can definitely try that. I'll have to look at a pdf for USICT's result first.
I'll update any progress related to this on this issue.

**Comment by ankushgarg1998** [comment]
Hey @Eshaan7 
I'm in the process of adding USICT to IPU Ranklist. I have some questions about the courses offered by USICT.

Can we connect for a quick call?

**Comment by ankushgarg1998** [comment]
Done and done. 🔥

**Comment by ankushgarg1998** [comment]
Thanks @Eshaan7 for all the help man.
