### ISSUE TITLE
Counting backlogs and updating as soon as they are cleared.

### ISSUE THREAD

**Issue by AIEnthusias-t** [ankushgarg1998/ipu-ranklist#19]

**Comment by ankushgarg1998** [comment]
Hi @AIEnthusias-t 
Your Issue is duplicate of #16 

So, I'm modifying it a little.

**Comment by ankushgarg1998** [comment]
- [ ] Counting semester-wise and overall backlogs.
- [ ] Displaying them in the profile and ranklist section.
- [ ] Updating them, when cleared.

**Comment by ankushgarg1998** [comment]
Fixed.
Subject marks show a 'backlog' tag and that tag is removed, when backlog is cleared.
@AIEnthusias-t
