### ISSUE TITLE
Multiple ranking criteria

### ISSUE THREAD

**Issue by rajatmw1999** [ankushgarg1998/ipu-ranklist#25]
The colleges and university are ranking students based on their overall CGPA instead of the percentage. The criteria can be changed in ipu-ranklist to rank them according to cgpa for a better understanding of the student's rank.

**Comment by ankushgarg1998** [comment]
Or better we could give provide separate ranklists for multiple criterias like
- On CGPA
- On Percentage
- On Credit Percentage

**Comment by ankushgarg1998** [comment]
Done. Please do test it @rajatmw1999
