### ISSUE TITLE
visualization

### ISSUE THREAD

**Issue by abhishek-parashar** [ankushgarg1998/ipu-ranklist#27]
proper visualization is required for monitoring marks gain or fall and, a pie chart to show percentage of marks in a particular subject of the total percentage.
more can be added just a few examples I can think of right now.

**Comment by Animesh-Ghosh** [comment]
[Friends Don't Let Friends Use Pie Charts](https://excelforeducators.blogspot.com/2011/11/friends-dont-let-friends-use-pie-charts.html). You are a friend, right?

**Comment by ankushgarg1998** [comment]
- [ ] Profile Page
- - [ ] Horizontal Stacked Bar Graph (Semester section)
<sub>**Stacked**: To show Internal and external marks separately.</sub>
<sub>**Horizontal**: Because vertical won't fit in mobile view for a semester that has many subjects.</sub>
<sub>**Bar**: To show subject-wise comparison.</sub>
- - [ ] Percentage Line Chart (Overall Section)
- - [ ] GPA Line Chart (Overall Section)
<sub>**Line**: To show the trend of rise or fall through the semesters.</sub>

**Comment by ankushgarg1998** [comment]
- [ ] Ranklist Section (Still working on the design phase)
- Could be a line chart showing class' performance.
- Should display class average
- How will a chart of 200 students' percentage/gpa fit on a mobile screen horizontally 😂 ?

**Comment by abhishek-parashar** [comment]
Leave the class average part, Mostly students are not interested in knowing what the class trend is ( I am not XD) 
Add graphs for the student section only 
talking about the fitting part I don't know about java script but python has a tool named as plotly which can create interactive plots in a window, that is it can expand contract, you can move around in different dimensions etc.

**Comment by ankushgarg1998** [comment]
<img width="1421" alt="Screenshot 2020-05-08 at 1 48 12 AM" src="https://user-images.githubusercontent.com/22600172/81340749-fd43dd00-90cd-11ea-9362-badf1ea7f1fd.png">

**Comment by ankushgarg1998** [comment]
![WhatsApp Image 2020-05-08 at 1 39 38 AM](https://user-images.githubusercontent.com/22600172/81340835-249aaa00-90ce-11ea-8dee-9cd1e2ceac2d.jpeg)

**Comment by ankushgarg1998** [comment]
> * [x]  Ranklist Section (Still working on the design phase)
> * Could be a line chart showing class' performance.
> * Should display class average
> * How will a chart of 200 students' percentage/gpa fit on a mobile screen horizontally 😂 ?

Nailed it.
