### ISSUE TITLE
students who have left the college or have changed their branch still in the rank list.

### ISSUE THREAD

**Issue by abhishek-parashar** [ankushgarg1998/ipu-ranklist#29]
obvious reasons for eating away ranks. Can't show to my mum with this excuse.

**Comment by ankushgarg1998** [comment]
The students who migrate from their prior branch get a new enrolment number. There (I believe) is no way to connect these two enrolment numbers.

The best I can do is probably give an option to filter out the people who have migrated into your class (but that'll also filter out the Lateral Entry (LE) folks).

So this issue is not solvable according to me.

Any help is appreciated.

**Comment by abhishek-parashar** [comment]
one thing which you can do is the total marks would be different for students who have migrated. 
1.Perform a search of the students with less total marks in all the branches
2.select the one with same name
3.update according to the branch
may require a lot of effort but would surely solve the issue.

**Comment by ankushgarg1998** [comment]
@abhishek-parashar 
1. The total marks of LE students are also less than that of the rest.
2. There could be two students with the same name migrating in the same year. One migrated from ECE to CSE. One migrated from EEE to IT. There's now way to know which one migrated to where.

**Comment by abhishek-parashar** [comment]
1. I am not asking to remove the le students. Less marks only acts as a searching technique or separation from the rest. Then you have to perform the search for students having the same name. 
2. Agreed but having two students who must have migrated in the same year with the same name from the same college would be highly unlikely. 
That's why I said there would be a lot of work for you to do.

**Comment by ankushgarg1998** [comment]
![Screenshot 2020-06-08 at 7 42 17 PM](https://user-images.githubusercontent.com/22600172/84040366-2b178c80-a9c0-11ea-9a31-61f9a7b3acb8.png)
Urgent work needed. Ab toh Parth Bhaiya ne bhi bol dia hai.

**Comment by ankushgarg1998** [comment]
- [ ] By default remove the students who've migrated. (Filtering on latest sem)
- [ ] Add a simple checkbox to allow the inclusion of (potential) migrators.

**Comment by ankushgarg1998** [comment]
This feature's added.
