### ISSUE TITLE
Rankings of BVCOE for 2018-2022 cannot be found.

### ISSUE THREAD

**Issue by thisispratt** [ankushgarg1998/ipu-ranklist#30]
### Screenshot:

![image](https://user-images.githubusercontent.com/40731031/76458428-91f8ca00-6400-11ea-8f16-423246ac4906.png)

**Comment by ankushgarg1998** [comment]
Holy shit 😦. Thanks for raising this this @thisispratt. This was a big one.

Has been fixed now.
