### ISSUE TITLE
Incorrect Batch/Year dropdown values.

### ISSUE THREAD

**Issue by ankushgarg1998** [ankushgarg1998/ipu-ranklist#40]
Unifying the list form of all the courses has broken then batch/year dropdown. It is showing 4 year long spans for 3 year long courses.

**Comment by ankushgarg1998** [comment]
Thanks to Akash Gupta for reporting this.

**Comment by akug17** [comment]
Appreciate it bro!

**Comment by ankushgarg1998** [comment]
Fixed.
