### ISSUE TITLE
Option for migrators to see their combined result

### ISSUE THREAD

**Issue by ankushgarg1998** [ankushgarg1998/ipu-ranklist#43]
Option for migrators to see their combined results (only for profile section) using both enrollment numbers.

![Screenshot 2020-06-10 at 12 01 48 AM](https://user-images.githubusercontent.com/22600172/84186078-97bc8500-aaad-11ea-9396-1ebefbdb1a00.png)

**Comment by imarchit19** [comment]
This could be implemented for students who got upgraded as well.

**Comment by ankushgarg1998** [comment]
Yes @imarchit19. I believe they get a new enrollment number too.

**Comment by ankushgarg1998** [comment]
After more than a year of deciding to implement this feature. And after many many mails and messages, finally took out time to implement it.

https://www.ipuranklist.com/upgradation-student

Jai Mata Di.

**Comment by imarchit19** [comment]
Thanks a lot!
Much Appreciated.
