### ISSUE TITLE
Highest Marks highlight if anyone has in that particular subject

### ISSUE THREAD

**Issue by ShubhamChaudharyy** [ankushgarg1998/ipu-ranklist#45]

**Comment by ankushgarg1998** [comment]
<img width="1440" alt="Screenshot 2020-06-20 at 10 17 54 PM" src="https://user-images.githubusercontent.com/22600172/85207067-e4bd1880-b343-11ea-9ef8-8a0cc0522902.png">


Hey @ShubhamChaudharyy 
This feature already exists. :D

**Comment by ShubhamChaudharyy** [comment]
> <img alt="Screenshot 2020-06-20 at 10 17 54 PM" width="1440" src="https://user-images.githubusercontent.com/22600172/85207067-e4bd1880-b343-11ea-9ef8-8a0cc0522902.png">
> 
> Hey @ShubhamChaudharyy
> This feature already exists. :D

Didnt see the updated Version..Amazing btw

**Comment by ankushgarg1998** [comment]
Glad, you liked it @ShubhamChaudharyy :)
