### ISSUE TITLE
How is the cgpa calculated? 

### ISSUE THREAD

**Issue by mewcifur28** [ankushgarg1998/ipu-ranklist#55]
The formula prescribed for Cgpa in the ordinance is being used to calculate the credit percentage, how are SGPA and CGPA calculated in this application?

**Comment by ankushgarg1998** [comment]
The formula used for calculation of SGPA and CGPA is the same as mentioned at the back of our official semester mark sheets.

![photo6116337775637801410](https://user-images.githubusercontent.com/22600172/88452822-778b2e80-ce7f-11ea-9bdd-4ee6178f72a0.jpg)

**Comment by ankushgarg1998** [comment]
Hey @mewcifur28 
I'm assuming, I've answered your question. I'm closing this issue.

Please feel free to reopen this or create a new one, if you expect further clarification.
