### ISSUE TITLE
Add theme-colour meta tag for Chrome on Android

### ISSUE THREAD

**Issue by Animesh-Ghosh** [ankushgarg1998/ipu-ranklist#73]
Currently this is how the site looks in Chrome on Android (Android 6 in my case):
![image](https://user-images.githubusercontent.com/34956994/95653274-1d604800-0b15-11eb-8de3-236b9124265c.png)

It would be a nice touch if the `theme-color` meta tag is added which is consistent with the theme of the site.

My humble suggestion:
```html
<meta name="theme-color" value="#212529"/>
```

**Comment by ankushgarg1998** [comment]
That's actually a really good suggestion man. I feel like #172E58 color matches with the website better.

Also, I had to use this code:
```html
    <!-- Chrome, Firefox OS and Opera -->
    <meta name="theme-color" content="#172E58">
    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#172E58">
    <!-- iOS Safari -->
    <meta name="apple-mobile-web-app-status-bar-style" content="#172E58">
```

<img src="https://user-images.githubusercontent.com/22600172/95672468-9ff11200-0bbe-11eb-955f-0ea37d05f1a7.jpeg" width=400>

**Comment by Animesh-Ghosh** [comment]
IMO Windows Phone doesn't seem to have a significant enough user base for the site to support it. However, the final decision is obviously yours.

Also, I yanked the colour code from the navbar component, and since I couldn't see how it would look on mobile, that colour seemed to be good enough. However, your selection seems to go with the theme perfectly.

**Comment by ankushgarg1998** [comment]
Cool. I'll integrate it in the next release and close this issue once it's live.

**Comment by ankushgarg1998** [comment]
Live now. :fire:
