### ISSUE TITLE
Wrong Percentage Criteria

### ISSUE THREAD

**Issue by gauravjain2** [ankushgarg1998/ipu-ranklist#80]
In GGSIPU, percentage is calculated as CGPA*10 
The website take it in term of marks, which is not the actual case.
Please Check.

**Comment by ankushgarg1998** [comment]
Hey @gauravjain2 
Thanks for pointing this out. 

Seems there is some evidence to support this. Had no clue, this is the case and I just graduated 😂

**Comment by ankushgarg1998** [comment]
[ordinanc11020815.pdf](https://github.com/ankushgarg1998/ipu-ranklist/files/5869424/ordinanc11020815.pdf)

^ Evidence

**Comment by ankushgarg1998** [comment]
cc @Eshaan7
This is where we'll be tracking it.

**Comment by ankushgarg1998** [comment]
Added Equivalent Percentage in student views and made GPA the default ranking criteria.

**Comment by ankushgarg1998** [comment]
![Screenshot 2021-03-12 at 11 46 10 PM](https://user-images.githubusercontent.com/22600172/110981415-2340aa80-838d-11eb-8e4f-5611d57203cc.png)
![Screenshot 2021-03-12 at 11 46 38 PM](https://user-images.githubusercontent.com/22600172/110981467-32bff380-838d-11eb-8e66-1c501474d2e7.png)

**Comment by gauravjain2** [comment]
The CGPA is rounded off to 2 decimal places and then equivalent percentage is calculated by multiplying it by 10.

So let's say, I got CGPA of 8.893
So my CGPA will be counted at 8.89 and percentage will be 88.9% not 88.93%

**Comment by ankushgarg1998** [comment]
The new build fixes it.
Also, the three decimal places were just not needed. IPU uses 2 decimal places. So I've changed all the GPAs and percentages to 2 decimal places.
