### ISSUE TITLE
Send Notification on Phone after results are out

### ISSUE THREAD

**Issue by Jassi10000-zz** [ankushgarg1998/ipu-ranklist#93]
I think if  the site contains a feature of sending notification to Student's registered number 
I would be really benefitial 
We have a nice Node.Js library available for that  called  " Twilio"  which can make implementation of this feature easy

**Comment by ankushgarg1998** [comment]
Hey @Jassi10000 

IPU Ranklist doesn't support text notification as of now, given the pricing of Twilio is a little out of my budget 😛  and I just can't keep up with being compliant with TRAI.

However, if you're open to using Telegram, we have a great bot, that notifies not just about Results, but also Datasheets and circulars. It only notifies about what you subscribe to, so you don't have to worry about unnecessary notifications.

I urge you to give it a try: [IPU Ranklist BOT 🤖 ](https://github.com/ankushgarg1998/ipuranklist-bot)

**Comment by Jassi10000-zz** [comment]
No issues with that, Twilio was just a suggestion from my side as you website is quite popular among all the colleges of IPU 
so was thinking of some large-scale feature

I looked upon the bot repo , looks cool
Thanks for this , will definitely try this ❤
