### ISSUE TITLE
Classify results according to Colleges

### ISSUE THREAD

**Issue by Jassi10000-zz** [ankushgarg1998/ipu-ranklist#94]
The site is built very awesome ❤
One thing I would like to see is classification of results according to Colleges 
as this can help teachers and even students to see the progress of each student and would not have to type Roll No each time to see result 
This way they can analyse their growth and also can know how much they have to improve in context of others to gain a nice percentile which will eventually boost confidence

**Comment by ankushgarg1998** [comment]
Hey @Jassi10000 

Done. What else you got?

**Comment by Jassi10000-zz** [comment]
Buddy , what am getting is not classified according to the colleges
I simply get a input box to enter my roll no and see my result
That's it

**Comment by ankushgarg1998** [comment]
Maybe check again? :D

**Comment by Jassi10000-zz** [comment]
Ya , now its same as I expected 
gr8 ❤
